const actionTypes = {
  GET_USER: 'GET_USER',
  ADD_USER: 'ADD_USER',
  EMPTY_USER: 'EMPTY_USER',
  GET_WORDCOUNTS: 'GET_WORDCOUNTS',
  ADD_WORDCOUNT: 'ADD_WORDCOUNT',
  UPDATE_WORDCOUNT: 'UPDATE_WORDCOUNT',
  DELETE_WORDCOUNT: 'DELETE_WORDCOUNT',
  EMPTY_WORDCOUNTS: 'EMPTY_WORDCOUNTS',
};

export default actionTypes;
